version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
#  redis:
#    image: "redis:alpine"

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
#      - redis
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=django_react_chat_example_project
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=django_react_chat_example_project


